# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "docsy-pwsh"
license = "MIT"
licenselink = "https://github.com/microsoft/Documentarian/blob/main/Source/Hugo/docsy-pwsh/LICENSE"
description = "A delightful theme for documenting PowerShell projects"
homepage = "https://microsoft.github.io/Documentarian/theme"
tags = ['docs', 'docsy', 'documentation', 'PowerShell', 'pwsh']
features = []
min_version = "0.104.0"

authors = [
  { name = "The Documentarian Team", homepage = "https://microsoft.github.io/Documentarian" },
  { name = "Microsoft", homepage = "https://microsoft.com" },
]

# If porting an existing theme
[original]
name = "Docsy"
homepage = "https://docsy.dev"
repo = "https://github.com/google/docsy"
