name: 🛠💡 Code Proposal
description: >-
  Suggest a new feature or change to an existing one.
labels:
  - enhancement
  - needs-triage
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: >-
        These steps are required. After you've completed each step, check the box for it before
        moving on.
      options:
        - label: >-
            **Accepted Idea:** Proposals in this project are created based on ideas that have been
            marked as `Accepted` in their [Discussion](https://github.com/microsoft/Documentarian/discussions/categories/code-proposals).
            Before you file an issue for a feature or change, create a discussion. If you file an
            issue without a discussion, the team may convert it into one.
          required: true
        - label: >-
            **Existing Issue:** Search the existing issues and discussions for this repository. If
            there is an issue or discussion that fits your needs do not file a new one. Subscribe,
            react, or comment on that issue or discussion instead.
          required: true
        - label: >-
            **Descriptive Title:** Write the title for this issue as a short synopsis. If possible,
            provide context. For example, "Add `Get-Foo` cmdlet to Documentarian module" instead of
            "New cmdlet."
          required: true
  - type: dropdown
    id: module
    validations:
      required: true
    attributes:
      label: Module
      description: >-
        Select the name of the module or modules this feature or idea is for.
      multiple: true
      options:
        - Documentarian
        - Documentarian.DevX
        - Documentarian.MarkdownLint
        - Documentarian.MicrosoftDocs
        - Documentarian.ModuleAuthor
        - Documentarian.Vale
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: >-
        Write a clear and concise description of the proposed feature or change. Why is it needed?
        What gap will it fill? Who is the intended user? What scenarios will it address?
      placeholder: |
        Try formulating the need for this feature or change as a user story.

        > As a user of <module>, I want <feature or change> so that <synopsis of value>.
  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add context and help the team
        understand the proposed feature or change.
