name: 📄💡 Document proposal
description: >-
  Suggest a new document or major rewrite of an existing one.
labels:
  - documentation
  - enhancement
  - needs-triage
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: >-
        These steps are required. After you've completed each step, check the box for it before
        moving on.
      options:
        - label: >-
            **Accepted Idea:** Proposals in this project are created based on ideas that have been
            marked as `Accepted` in their [Discussion](https://github.com/michaeltlombardi/DocumentarianModules/discussions/categories/ideas).
            Before you file an issue for new document or a rewrite, create a discussion. If you file
            an issue without a discussion, the team may convert it into one.
          required: true
        - label: >-
            **Existing Issue:** Search the existing issues and discussions for this repository. If
            there is an issue or discussion that fits your needs do not file a new one. Subscribe,
            react, or comment on that issue or discussion instead.
          required: true
        - label: >-
            **Descriptive Title:** Write the title for this issue as a short synopsis. If possible,
            provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."
          required: true
  - type: dropdown
    id: module
    validations:
      required: true
    attributes:
      label: Module
      description: >-
        Select the name of the module or modules this documentation is for.
      multiple: true
      options:
        - Documentarian
        - Documentarian.DevX
        # - Documentarian.MarkdownLint
        # - Documentarian.MicrosoftDocs
        # - Documentarian.MicrosoftDocs.PSDocs
        # - Documentarian.ModuleAuthor
        # - Documentarian.Vale
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: >-
        Write a clear and concise description of the proposed document. Why is it needed? What gap
        will it fill? Who is the intended audience? What scenarios will it address?
      placeholder: |
        Try formulating the need for this documentation as a user story.

        > As a user of <module>, I need a document about <topic> so that <synopsis of value>.
  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add context and help the team write
        the documentation.
  - type: dropdown
    id: type
    validations:
      required: true
    attributes:
      label: Proposed Content Type
      description: >-
        Choose the type or types of documentation required.
      multiple: true
      options:
        - Cmdlet Reference
        - About Topic
        - Concept
        - Other / Unknown
  - type: input
    id: title
    validations:
      required: false
    attributes:
      label: Proposed Title
  - type: textarea
    id: related_documents
    validations:
      required: false
    attributes:
      label: Related Articles
      description: >-
        Provide a list of links to the documentation page(s) that are related to this request. Use
        the markdown list syntax for each item. If the entire article is relevant, just link to the
        permalink for its source or the live page. If only a section of the article is relevant, use
        the permalink to the lines for the most relevant section of the source or the anchor link to
        the nearest header for the relevant content instead of the page itself.
      placeholder: |
        - https://github.com/michaeltlombardi/DocumentarianModules/blob/211f4d77e387c52659428be15f208a3e137ff1cc/Documentarian.Vale/Docs/Reference/Test-Vale.md
