name: Analyze repository
on:
  pull_request:
    branches:
      - main
jobs:
  analyze_github:
    name: GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Analyze repository
        uses: microsoft/ps-rule@46451b8f5258c41beb5ae69ed7190ccbba84112c # v2.9.0
        with:
          modules: "PSRule.Rules.GitHub"
  analyze_msft_oss:
    name: Microsoft OSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run PSRule analysis
        uses: microsoft/ps-rule@46451b8f5258c41beb5ae69ed7190ccbba84112c # v2.9.0
        with:
          modules: "PSRule.Rules.MSFT.OSS"
          prerelease: true
