name: Test Modules

on:
  pull_request:
    paths:
      - 'Projects/Modules/*/Source/**'
      - 'Projects/Modules/*/Tests/**'
      - 'Projects/Modules/*/.DevX.jsonc'

defaults:
  run:
    shell: pwsh

jobs:
  test_modules:
    name: PowerShell
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - Documentarian
          - Documentarian.DevX
          - Documentarian.MarkdownBuilder
          - Documentarian.MicrosoftDocs
          - Documentarian.ModuleAuthor
          - Documentarian.Vale
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PowerShell modules
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild, PlatyPS, PowerShell-Yaml, PsIni -ErrorAction Stop
      - name: Test ${{ matrix.module }}
        run: |
          $PSVersionTable
          Get-Module -ListAvailable InvokeBuild, PlatyPS, PowerShell-Yaml, PsIni |
            Format-Table -Property Name, Version, Path
          Push-Location ./Projects/Modules
          Invoke-Build
          Push-Location ./${{ matrix.module }}
          Invoke-Build -Task Test
